version: '3'

#Compose preset by LukasL28 https://github.com/LukasL28

services:
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '80:80'
      - '81:81'  #Management Webinterface
      - '443:443'
    volumes:
      - npm_data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      proxy_bridge: #custom network where all containers using npm are beeing maped to 


  error_page:  #Nginx Web-Server vor hosting your custom 404 Page
    image: nginx:latest
    depends_on:
      - npm
    volumes:
     - 404_page:/usr/share/nginx/html:ro
    networks:
      proxy_bridge:

volumes: 
  npm_data:
  letsencrypt:
  404_page: #you index file vor the 404 page goes here
  
networks: #custom network where all containers using npm
  proxy_bridge:
    name: proxy_bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16  #change if this subnet is already in use
          gateway: 172.25.0.1