#------------------------------------------------------------------------------------
#This uses the Preset provided by Pterodactyl!! I just fixed some things to run on Portainer
#Compose preset by LukasL28 https://github.com/LukasL28
#More preset's here: https://github.com/LukasL28/Docker_compose-Collection
#------------------------------------------------------------------------------------


version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "CHANGEME"
    MYSQL_ROOT_PASSWORD: "CHANGEME"
  panel:
    &panel-environment
    APP_URL: "https://pterodactyl.example.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "yourEmail@example.com"
    MAIL_DRIVER: "mail"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    networks:
      default:
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    deploy:
      mode: replicated 
      replicas: 1
  cache:
    image: redis:alpine
    restart: always
    networks:
      default:
    deploy:
      mode: replicated 
      replicas: 1
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    networks:
      default:
      # traefik-public: #if you use traefik
    links:
      - database
      - cache
    volumes:
      - var:/app/var/
      - nginx:/etc/nginx/http.d/
      - certs:/etc/letsencrypt/
      - logs:/app/storage/logs
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    deploy:
      mode: replicated 
      replicas: 1
      # labels: #if you use traefik
      #   - traefik.enable=true
      #   - traefik.docker.network=traefik-public
      #   - traefik.http.routers.panel-http.rule=Host(`pterodactyl.example.com`)
      #   - traefik.http.routers.panel-http.entrypoints=http
      #   - traefik.http.routers.panel-http.middlewares=https-redirect
      #   - traefik.http.routers.panel-https.rule=Host(`pterodactyl.example.com`)
      #   - traefik.http.routers.panel-https.entrypoints=https
      #   - traefik.http.routers.panel-https.tls=true
      #   - traefik.http.routers.panel-https.tls.certresolver=le
      #   - traefik.http.services.panel.loadbalancer.server.port=80
networks:
  # traefik-public: #if you use traefik
  #   external: true
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
        
volumes:
  database:
  var:
  nginx:
  certs:
  logs:
  