#------------------------------------------------------------------------------------
#Compose preset by LukasL28 https://github.com/LukasL28
#More preset's here: https://github.com/LukasL28/Docker_compose-Collection
#------------------------------------------------------------------------------------

version: '3.2'

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    hostname: "portainer"
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      # - traefik-public # if you use traefik
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      # labels: # if you use traefik
      #   - traefik.enable=true
      #   - traefik.docker.network=traefik-public
      #   - traefik.http.routers.portainer-https.service=portainer
      #   - traefik.http.routers.portainer-http.rule=Host(`portainer.example.com`)
      #   - traefik.http.routers.portainer-http.entrypoints=http
      #   - traefik.http.routers.portainer-http.middlewares=https-redirect
      #   - traefik.http.routers.portainer-https.rule=Host(`portainer.example.com`)
      #   - traefik.http.routers.portainer-https.entrypoints=https
      #   - traefik.http.routers.portainer-https.tls=true
      #   - traefik.http.routers.portainer-https.tls.certresolver=le
      #   - traefik.http.services.portainer.loadbalancer.server.port=9000
networks:
  agent_network:
    driver: overlay
    attachable: true
  # traefik-public: if you use traefik
  #   external: true

volumes:
  portainer_data:
