version: '3'

#Compose preset by LukasL28 https://github.com/LukasL28

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    # environment:
      # PMA_HOST: #list host of mysql server here
    networks:
      proxy_bridge:
      # db_1 # list all networks of mysql server here
 
networks:
  proxy_bridge:
    external: true
  # db_1: # list all networks of mysql server here
  #   external: true 